sonar.projectKey=polyglot-devops-microservices
sonar.projectName=polyglot-devops-microservices
sonar.sourceEncoding=UTF-8

sonar.sources=frontend/src,services,proto
sonar.tests=services/transaction-service/tests,services/report-service/tests,services/budget-service/internal

sonar.exclusions=**/.next/**,**/.venv/**,**/node_modules/**,**/staticfiles/**,**/migrations/**,**/alembic/versions/**
